version: "3.6"
services:
  nginx:
    image: nginx:${NGINX_VERSION}-alpine
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
  php-web:
    build: 
      context: .
      dockerfile: ./docker/craftcms/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        PROJECT_TYPE: fpm
        CRAFT_FROM_IMAGE: php-fpm
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - ${DB_SERVICE}
      - nginx
  php-cli: &php-cli-service
    build:
      context: .
      dockerfile: ./docker/craftcms/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        PROJECT_TYPE: cli
        CRAFT_FROM_IMAGE: cli
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - ${DB_SERVICE}
  # php-worker:
  #   <<: *php-cli-service
  #   command: ["./craft", "queue/listen"]
  postgres:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - ${POSGRES_PORT:-5432}:5432
    environment:
      POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "-E UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT:-3306}:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:${REDIS_VERSION}-alpine
    ports:
      - ${REDIS_PORT}:6379
volumes:
  postgres_data:
  mysql_data: